service: "app:svc"
labels:
  owner: "your_name"
  project: "TelecoCustomerChurn"
include:
  - "final_model/*"
  - "app.py"
python:
  packages:
    - python-dotenv
    - pandas
    - numpy
    - pymongo
    - certifi
    - "pymongo[srv]==3.12"
    - scikit-learn
    - matplotlib
    - seaborn
    - scipy
    - pyyaml
    - mlflow
    - xgboost
    - imbalanced-learn
    - dagshub
    - bentoml
    - fastapi
    - cloudpickle
    - joblib
    # Add any other dependencies your model or preprocessor needs
  index-url: "https://pypi.org/simple"
docker:
  system_packages:
    - build-essential
    - curl
    - git
  python_version: "3.10"
  env:
    BENTOML_CONFIG: "/bento/bentoml_configuration.yaml"
  # Uncomment and edit if you have a custom Dockerfile
  # dockerfile: "./Dockerfile"
bentoml_version: "1.4.0"
# entrypoint: "bentoml serve app:svc"