columns:
  customerID:
    type: string
  gender:
    type: string
    allowed: ["Male", "Female"]
  SeniorCitizen:
    type: int
    min: 0
    max: 1
  Partner:
    type: string
    allowed: ["Yes", "No"]
  Dependents:
    type: string
    allowed: ["Yes", "No"]
  tenure:
    type: int
    min: 0
    max: 100
  PhoneService:
    type: string
    allowed: ["Yes", "No"]
  MultipleLines:
    type: string
    allowed: ["Yes", "No", "No phone service"]
  InternetService:
    type: string
    allowed: ["DSL", "Fiber optic", "No"]
  OnlineSecurity:
    type: string
    allowed: ["Yes", "No", "No internet service"]
  OnlineBackup:
    type: string
    allowed: ["Yes", "No", "No internet service"]
  DeviceProtection:
    type: string
    allowed: ["Yes", "No", "No internet service"]
  TechSupport:
    type: string
    allowed: ["Yes", "No", "No internet service"]
  StreamingTV:
    type: string
    allowed: ["Yes", "No", "No internet service"]
  StreamingMovies:
    type: string
    allowed: ["Yes", "No", "No internet service"]
  Contract:
    type: string
    allowed: ["Month-to-month", "One year", "Two year"]
  PaperlessBilling:
    type: string
    allowed: ["Yes", "No"]
  PaymentMethod:
    type: string
    allowed: ["Electronic check", "Mailed check", "Bank transfer (automatic)", "Credit card (automatic)"]
  MonthlyCharges:
    type: float
    min: 0
    max: 200
  TotalCharges:
    type: float
    min: 0
    max: 10000
  Churn:
    type: string
    allowed: ["Yes", "No"]
